title: La Spigolatrice
# description: Via Cagliari 25, Pisa - +39 050563151
# theme: minima
minima:
  skin: dark
# Add to plugins: list
plugins:
  - jekyll-remote-theme

# set up remote_theme
remote_theme: jekyll/minima