title: La Spigolatrice
description: Pisa
theme: just-the-docs

url: https://laspigolatrice.github.io/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/laspigolatrice/laspigolatrice.github.io