title: La Spigolatrice
# description: Via Cagliari 25, Pisa - +39 050563151
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jejyll-remote-theme

remote_theme: jekyll/minima

minima:
  skin: dark